# Generated by Django 4.1.5 on 2023-02-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_changed_post_created_post_published_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
