# Generated by Django 3.2.16 on 2023-01-27 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_type', models.CharField(choices=[('D', 'debit'), ('C', 'credit')], max_length=1)),
                ('payment_description', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=150, null=True)),
                ('document_number', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('fixed_expense', models.BooleanField(default=False)),
                ('bank_account', models.CharField(max_length=100)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('increase', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_the_bill', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
