# Generated by Django 4.1.5 on 2023-03-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='posting_type',
            field=models.CharField(choices=[('debit', 'debit'), ('creditj', 'credit')], max_length=50),
        ),
    ]
