# Generated by Django 4.2.3 on 2023-07-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_table_invoices_posting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_invoices',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='table_invoices',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='table_invoices',
            name='increase',
        ),
    ]
