# Generated by Django 4.2.3 on 2023-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_remove_table_invoices_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_invoices',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
