# Generated by Django 4.2.3 on 2023-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_table_invoices_posting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_invoices',
            name='paid_the_bill',
        ),
        migrations.AddField(
            model_name='table_invoices',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled')], default='pending'),
        ),
    ]
