# Generated by Django 4.2.3 on 2023-07-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_remove_table_invoices_paid_the_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_invoices',
            name='payment_date',
        ),
    ]
