# Generated by Django 4.2.3 on 2023-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_remove_table_invoices_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='posting_type',
            field=models.CharField(choices=[(0, 'debit'), (1, 'credit')], max_length=50),
        ),
    ]
