# Generated by Django 4.2.3 on 2023-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_table_invoices_posting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='posting_type',
            field=models.CharField(choices=[('0', 'debit'), ('1', 'credit')], max_length=50),
        ),
    ]
