# Generated by Django 4.2.2 on 2023-08-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_alter_table_invoices_posting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='posting_type',
            field=models.CharField(choices=[('expense', 'expense'), ('revenue', 'revenue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='table_invoices',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled')], default='pending'),
        ),
    ]
