# Generated by Django 4.2.4 on 2023-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_invoice_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('canceled', 'canceled'), ('overdue', 'overdue')], default='pending'),
        ),
    ]
