# Generated by Django 4.2.2 on 2023-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_table_invoices_card_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='table_invoices',
            name='payment_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='table_invoices',
            name='posting_type',
            field=models.CharField(choices=[('expense', 'expense'), ('revenue', 'revenue')], default='expense', max_length=50),
        ),
    ]
