# Generated by Django 4.2.2 on 2023-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_invoices',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
