# Generated by Django 4.2.2 on 2023-10-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_alter_card_card_alter_invoice_bank_invoice_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_invoices',
            name='fixed_expense',
        ),
    ]
