# Generated by Django 4.2.2 on 2023-06-30 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinfo', '0002_user_info_date_of_birth_user_info_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
