# Generated by Django 4.2.2 on 2023-06-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_user_info_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='name',
        ),
    ]
