# Generated by Django 4.2.2 on 2023-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_remove_user_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
