# Generated by Django 4.2.2 on 2023-07-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_user_info_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='biography',
            field=models.TextField(default='', max_length=300),
        ),
    ]
