# Generated by Django 4.2.2 on 2023-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0012_user_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='biography',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
