# Generated by Django 4.2.3 on 2023-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0016_user_info_changed_user_info_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='plan',
            field=models.CharField(choices=[('trial_period', 'trial period'), ('signature', 'signature'), ('free', 'free')], default='signature', max_length=50),
        ),
    ]
