# Generated by Django 4.2.3 on 2023-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0017_alter_account_plan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_plan',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_plan',
            name='plan',
            field=models.CharField(choices=[('trial_period', 'trial period'), ('signature', 'signature'), ('free', 'free')], default='trial period', max_length=50),
        ),
    ]
