# Generated by Django 4.2.2 on 2023-07-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0023_alter_account_plan_plan_subscription_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_history',
            name='date',
            field=models.DateTimeField(max_length=15),
        ),
    ]
