# Generated by Django 4.2.3 on 2023-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0026_alter_subscription_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='plan',
            field=models.CharField(choices=[('0', 'trial period'), ('1', 'signature'), ('2', 'free')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription_history',
            name='plan',
            field=models.CharField(choices=[('0', 'trial period'), ('1', 'signature'), ('2', 'free')], max_length=50),
        ),
    ]
