# Generated by Django 4.2.3 on 2023-07-21 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0027_alter_account_plan_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 13, 45, 45, 599483, tzinfo=datetime.timezone.utc)),
        ),
    ]
