# Generated by Django 4.2.3 on 2023-07-28 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0033_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 17, 43, 1, 793402, tzinfo=datetime.timezone.utc)),
        ),
    ]
