# Generated by Django 4.2.2 on 2023-08-08 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0040_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 23, 24, 40, 293208, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='account_plan',
            name='plan',
            field=models.CharField(choices=[('0', 'trial'), ('1', 'signature'), ('2', 'free')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription_history',
            name='plan',
            field=models.CharField(choices=[('0', 'trial'), ('1', 'signature'), ('2', 'free')], max_length=50),
        ),
    ]
