# Generated by Django 4.2.4 on 2023-08-14 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0051_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 12, 50, 9, 628615, tzinfo=datetime.timezone.utc)),
        ),
    ]
