# Generated by Django 4.2.4 on 2023-08-16 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0061_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 12, 26, 29, 110752, tzinfo=datetime.timezone.utc)),
        ),
    ]
