# Generated by Django 4.2.4 on 2023-08-22 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0066_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 14, 45, 40, 929935, tzinfo=datetime.timezone.utc)),
        ),
    ]
