# Generated by Django 4.2.2 on 2023-09-29 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0077_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 21, 32, 2, 930487, tzinfo=datetime.timezone.utc)),
        ),
    ]
