# Generated by Django 4.2.2 on 2023-10-27 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0095_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 23, 44, 23, 492656, tzinfo=datetime.timezone.utc)),
        ),
    ]
