# Generated by Django 4.2.4 on 2023-11-17 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0100_privacy_policy_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 13, 23, 29, 199586, tzinfo=datetime.timezone.utc)),
        ),
    ]
