# Generated by Django 4.2.2 on 2023-11-17 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0104_privacy_policy_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 50, 48, 963593, tzinfo=datetime.timezone.utc)),
        ),
    ]
