# Generated by Django 4.2.2 on 2023-11-17 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0105_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy_policy',
            name='privacy_policy_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacy_policy',
            name='service_terms_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 23, 16, 16, 187290, tzinfo=datetime.timezone.utc)),
        ),
    ]
