# Generated by Django 4.2.4 on 2023-11-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0106_privacy_policy_privacy_policy_pt_br_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 17, 30, 37, 127730, tzinfo=datetime.timezone.utc)),
        ),
    ]
