# Generated by Django 4.2.2 on 2023-11-25 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0107_alter_account_plan_date_limit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 15, 58, 43, 799432, tzinfo=datetime.timezone.utc)),
        ),
    ]
