# Generated by Django 4.2.2 on 2023-12-08 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0109_alter_account_plan_date_limit_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_plan',
            name='date_limit_plan',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 15, 48, 425315, tzinfo=datetime.timezone.utc)),
        ),
    ]
